/*
Weather

	http://wunderground.com
	http://www.accuweather.com/
	http://simuawips.com/
	http://www.tropicwx.com/


from: http://www.youtube.com/user/Suspicious0bservers?feature=watch

WORLD WEATHER:
    NDBC Buoys: http://www.ndbc.noaa.gov/
    Tropical Storms: http://www.wunderground.com/tropical/
    HurricaneZone Satellite Images: http://www.hurricanezone.net/westpaci...
    Weather Channel: http://www.weather.com/
    NOAA Environmental Visualization Laboratory: http://www.nnvl.noaa.gov/Default.php
    Pressure Maps: http://www.woweather.com/cgi-bin/expe...
    Satellite Maps: http://www.woweather.com/cgi-app/sate...
    Forecast Maps: http://www.woweather.com/weather/maps...
    EL DORADO WORLD WEATHER MAP: http://www.eldoradocountyweather.com/...
    TORCON: http://www.weather.com/news/tornado-t... [Tornado Forecast for the day]
    HURRICANE TRACKER: http://www.weather.com/weather/hurric...

US WEATHER:
    Precipitation Totals: http://www.cocorahs.org/ViewData/List...
    GOES Satellites: http://rsd.gsfc.nasa.gov/goes/
    THE WINDMAP: http://hint.fm/wind/
    Severe Weather Threats: http://www.weather.com/news/weather-s...
    Canada Weather Office Satellite Composites: http://www.weatheroffice.gc.ca/satell...
    Temperature Delta: http://www.intellicast.com/National/T...
    Records/Extremes: http://www.ncdc.noaa.gov/extremes/rec...


MISC Links:
    JAPAN Radiation Map: http://jciv.iidj.net/map/
    RADIATION Network: http://radiationnetwork.com/
    LISS: http://earthquake.usgs.gov/monitoring...
    QUAKES LIST FULL: http://www.emsc-csem.org/Earthquake/s...
    RSOE: http://hisz.rsoe.hu/alertmap/index2.php [That cool alert map I use]
    Moon: http://www.fourmilab.ch/earthview/pac...
*/
